### ISSUE TITLE
Autolock not working

### ISSUE THREAD

**Issue by paulrudy** [blacs30/bitwarden-alfred-workflow#103]
Autolock isn't working for me. I've given `LOCK_TIMEOUT` a value of 60, and successfully installed autolock with the keyword.

**Comment by blacs30** [comment]
It might take more time, up to 65 minutes for it to work. The agent runs every 5 minutes and checks the last usage.
The lock only happens if you haven't used Bitwarden for at least 60 minutes.

Can you run this command in a terminal to check that it doesn't throw any error exit codes, 0 is expected:

```
launchctl list | ag liso

SHOULD RETURN:

-       0       com.lisowski-development.alfred.bitwarden_lock
```

**Comment by luckman212** [comment]
@paulrudy just a note: `ag` (silver searcher) doesn't come installed by default... so try `launchctl list | grep liso` if @blacs30's command doesn't work

**Comment by blacs30** [comment]
@luckman212 of course. completely overlooked that. thanks for that.

**Comment by paulrudy** [comment]
Thanks. It has not locked itself in over 24 hours. When I run `launchctl list | grep liso`, it returns:
```
-	0	com.lisowski-development.alfred.bitwarden_lock
-	127	com.lisowski-development.alfred.bitwarden_autosync
```

**Comment by blacs30** [comment]
@paulrudy sorry for my late reply.
Error 127 happens when a binary/executable is not found but that is regarding the sync daemon, you could try to reinstall it.

Regarding the auto lock you could debug it the following way:

```
file=$(cat ~/Library/LaunchAgents/bw_auto_lock.sh_lock_agent.plist | grep Users | sed -n 's:.*<string>\(.*\)</string>.*:\1:p')
sed '/last-usage ].*/i set -x' "${file}" > "${file}".tmp && mv "${file}".tmp "${file}"
bash "${file}" 1
```

This will get the `bw_auto_lock.sh` in the Alfred directory from the LaunchAgents plist config.
Then it adds a `set -x` close to the end where it compares the last-usage timestamp (written by the Alfred workflow into the data dir of the workflow) with the current timestamp 
And at last the file is executed with a lock timeout of 1 minute and you can see more output, which you also could post here in case it's still not working.
