### ISSUE TITLE
Issue using on multiple machine

### ISSUE THREAD

**Issue by yqrashawn** [blacs30/bitwarden-alfred-workflow#106]
I'm currently using this workflow on two machines. I sync the `Alfred.alfredpreferences` and `~/Library/Application Support/Bitwarden CLI` with dropbox.

This workflow works well on one machine. The sync bitwarden secrets option action in .bitconfig runs forever and sync nothing on the other machine.

I found that the bw cli use a session key for the auth info. Is this the supposed behavior?

**Comment by blacs30** [comment]
If you sync also the `~/Library/Application Support/Bitwarden CLI` directory then the workflow is only going to work on one machine.
The reason is that the file in the `Bitwarden CLI` directory works with a session key which the workflow stores in the macOS keychain. You can use these [cli helpers ](https://github.com/luckman212/bitwarden-cli-helpers) to use the bw cli and the workflow on the same machine, but if you want to use the same `Bitwarden CLI` directory on 2 machines you need to sync that session key as well.
Why not just syncing the `Alfred.alfredpreferences` and leave the `Bitwarden CLI`directory unsynced? That's how I do it.

**Comment by yqrashawn** [comment]
> Why not just syncing the Alfred.alfredpreferences and leave the Bitwarden CLIdirectory unsynced? 
That's what I used to do. But it only works on one machine. I'll try again.
