### ISSUE TITLE
No more password stored

### ISSUE THREAD

**Issue by damiencuvillier** [blacs30/bitwarden-alfred-workflow#107]
I had an issue with sync for a few weeks : 
* many password items were missing in my list / search did not give exhaustive results
* synchronization seemed to not work fully

Here is my request : 
![image](https://user-images.githubusercontent.com/3856306/133460540-fac02834-1d63-4149-895d-af1c90cdf040.png)
... only 2 result. 
Same request on MacOSX native client gives 8 results : 

![image](https://user-images.githubusercontent.com/3856306/133460791-7a519879-889a-4094-8b87-cc093d205236.png)

Same request with bitwarden-cli command line gives me also 8 results ... 
![image](https://user-images.githubusercontent.com/3856306/133461071-3e437c7a-39d0-4c01-871a-c7f71fcf3403.png)

So I've tried to 

* purge cache
![image](https://user-images.githubusercontent.com/3856306/133460304-6cf0917c-5c53-4f6e-ac2c-c24495ceaa70.png)
* reauthenticate : it looks ok
* resync manually
![image](https://user-images.githubusercontent.com/3856306/133460358-fe2e15f7-234b-4e9e-8eb5-9798700ee94a.png)
* But I still miss some items.  

What should I do ?

**Comment by luckman212** [comment]
@damiencuvillier Could this just be a discrepancy between Alfred's matching algo vs. the native app?

Check that your script filter is set to word matching... just a guess

![CleanShot 2021-09-15 at 11 21 31](https://user-images.githubusercontent.com/1992842/133462048-006aae50-e442-4594-b213-e06bda0ac3f3.png)

**Comment by damiencuvillier** [comment]
That's my settings indeed. 
Anything else ?

How can I get raw request send to bitwarden-cli ?

**Comment by blacs30** [comment]
Raw search requests are not send to the Bitwarden Cli, that would be too slow in connection with Alfred and live updates.
Can you set those 2 workflow vars to false and see how that changes:
`TITLE_WITH_URLS `, `TITLE_WITH_USER`

It seems like Alfred searches case sensitive in your example, does it find 6 items if you type `redmine` with lower case chars?

**Comment by blacs30** [comment]
Searches are not done case sensitive on my side, that's not the issue here then I guess.

I double checked with an export of bitwarden.com and do have the same number of items in the Alfred Bitwarden workflow.

You can see if the items are present, for whatever reason just not appearing in the search, doing these steps:

1. login to bitwarden with the workflow and sync ones
1. run in the terminal these commands

```
cd ~'/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/com.lisowski-development.alfred.bitwarden'
rm com.lisowski-development.alfred.bitwarden.log*
```

3. Run the bitwarden workflow ones (don't search for anything though)
4. back in the terminal run this command, which should open the log file which contains all items of your bitwarden vault (no passwords visible), here you search for `redmine` again and hopefully see it appearing.

```
open com.lisowski-development.alfred.bitwarden.log
```
5.  Search also for `map[`, that gives you the total amount of secrets you do have. I have 562 and I don't know if there is any problem with very big amounts of secrets.
