### ISSUE TITLE
Not able to login through alfred (Email address is invalid error)

### ISSUE THREAD

**Issue by siddharthalodha** [blacs30/bitwarden-alfred-workflow#76]
Not able to login through the extension as getting this error. Tried login using the cli, was able to login but alfred extensions can't fetch passwords in that case.

Using latest version of alfred, bitwarden extension as well as cli. 

```

[18:51:27.765] Bitwarden v2[Script Filter] Processing complete
[18:51:27.767] Bitwarden v2[Script Filter] Passing output '(
    login,
    "siddhartha.2608@gmail.com",
    0,
    "Authenticator-app"
)' to Conditional
[18:51:27.770] Bitwarden v2[Conditional] Processing complete
[18:51:27.771] Bitwarden v2[Conditional] Passing output '(
    login,
    "siddhartha.2608@gmail.com",
    0,
    "Authenticator-app"
)' to Run Script
[18:51:39.993] Bitwarden v2[Run Script] Processing complete
[18:51:39.994] Bitwarden v2[Run Script] Passing output 'Error: Email address is invalid.
' to Post Notification
```

**Comment by claas-fridtjof-lisowski** [comment]
Do you have a custom server url specified? If I run a test with the provided email address I get a different error (of course I have entered a wrong password)

`Error: Username or password is incorrect. Try again.`

**Comment by siddharthalodha** [comment]
Hey, 
I am using all the default options. I have 2FA enabled though.

**Comment by blacs30** [comment]
Have you tried to login via bitwarden cli in the terminal itself? Does that work?

**Comment by siddharthalodha** [comment]
Yes, I am able to login using the terminal cli. Just tried on a newer mac. Same issue.

**Comment by lyczak** [comment]
The issue seems tied to how command-line arguments are getting passed from Alfred to `bitwarden-auth-flow.js`. From what I can tell, the bash command which gets called by Alfred during the login/unlock process seems to be adding weird formatting that screws up the argument parsing in the script.

```sh
/usr/bin/osascript bitwarden-auth-flow.js $1 $2 $3 $4 # this script in Alfred
# once args are passed from the previous workflow step, becomes:
/usr/bin/osascript bitwarden-auth-flow.js ( login, "email@example.com", 0, "Authenticator-app" )
```

What's happening is that when `bitwarden-auth-flow.js` tries to parse it's arguments, the array of args looks like this:
`(` | `login,` | `"email@example.com",` | `0,` | `"Authenticator-app"` | ` )`
There are a bunch of problems here, including the parentheses being interpreted as arguments, to the commas and quotes being part of the arguments too. I'm not 100% sure why Alfred is passing arguments in this way. Maybe the whole parentheses block was just a literal string it received as one of the arguments and the problem is further up the chain.

I didn't have time to completely fix this, so my **quick-and-dirty fix** was just to sorta hardcode the variables being initialized from the args by hand inside `bitwarden-auth-flow.js`

```js
var mode = arg[1] // increment to account for the parentheses at the beginning
var modeSet = "unlock" //unchanged
var email = "email@example.com" // hardcode your email address

// ...

var totpInt = 0 // hardcode your TOTP type
var totpStr = "Authenticator-app"
```

For details regarding TOTP numbers/values, see the [Bitwarden CLI docs](https://bitwarden.com/help/article/cli/#enums)

**Comment by blacs30** [comment]
@siddharthalodha  can you please try again with the new [version 2.3.0](https://github.com/blacs30/bitwarden-alfred-workflow/releases/tag/2.3.0) I've changed the way how I pass the parameters to the script which handles the login

**Comment by siddharthalodha** [comment]
Thanks, it is working perfectly now !
