### ISSUE TITLE
I have an endless loop

### ISSUE THREAD

**Issue by edheltzel** [blacs30/bitwarden-alfred-workflow#99]
not sure what is up

my `BW_EXEC` is set to `/opt/homebrew/bin/bw`
`PATH` is set to /usr/bin:/usr/local/bin:/usr/local/sbin:/usr/local/share/npm/bin:/usr/bin:/usr/sbin:/opt/homebrew/bin/bw`

[![loop.th.gif](https://s5.gifyu.com/images/loop.th.gif)](https://gifyu.com/image/GL8i)

**Comment by blacs30** [comment]
Hi @edheltzel ,
thanks for this gif.
I was only in one situation able to reproduce the loop for a few seconds, until Bitwarden finished the login process.
Typically after logging in the window with the 2fa code hangs 1 or 2 seconds and then there is also a notification appearing in the macOS style that Bitwarden is logged in. 
I don't see that in the gif, maybe it's cut off? Do you get such a login confirmation?
Can you open Alfred and run the workflow in debug mode and check the logs if they complain about something, possibly some special characters in the password or so that leads to errors?

**Comment by edheltzel** [comment]
@blacs30 

https://webmshare.com/play/q1wP3

Here is the log from debug mode: 
https://gist.github.com/edheltzel/18e66b0844b2c7cb5daa71878e473ddb

**Comment by luckman212** [comment]
i'm on my mobile so take with grain of salt, but looking at your debug output it appears that `node` isn't in your `PATH` or is not installed correctly.....

**Comment by blacs30** [comment]
good catch @luckman212 
```
[07:52:30.863] STDERR: Bitwarden v2[Run Script] Error: env: node: Not a directory
[07:52:30.864] Bitwarden v2[Run Script] Processing complete
[07:52:30.872] Bitwarden v2[Run Script] Passing output 'Error: env: node: Not a directory
' to Post Notification
```

Possibly I can catch this error so that it's more obvious what's happening to the user.

**Comment by edheltzel** [comment]
I dont generally include node in my path since I user a a couple of different versions. 
But when I do include it in the `$PATH` everything is working as expected.

**Comment by blacs30** [comment]
Good to hear. In the normal shell it's probably reachable but for Alfred no node was found at all which of course leads to problems. Nice that it's working now. Hope the workflow is helpful for you.
